'use strict';

module.exports = {
    NONE: '',
    MAIN: '_MAIN',
    SELECTSTOP: '_SELECTSTOP',
    SELECTROUTE: '_SELECTROUTE',
    DIRECTDEPARTURE: '_DIRECTDEPARTURE',
    SELECTSTANDARDSTOP: '_SELECTSTANDARDSTOP',
};